// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_JZqtygKVdrF1RrS-6O1CCaZsrW46_Gc',
    appId: '1:840177546760:web:85ccd8089f8c08e21583bd',
    messagingSenderId: '840177546760',
    projectId: 'flutter-e-commerce-app-4cc9a',
    authDomain: 'flutter-e-commerce-app-4cc9a.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-app-4cc9a.firebasestorage.app',
    measurementId: 'G-JS2VF0FHD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzcLI6eYaFtwdIdNPswNGro47Cc_dUlA',
    appId: '1:840177546760:android:cc29e1a9e00d99b91583bd',
    messagingSenderId: '840177546760',
    projectId: 'flutter-e-commerce-app-4cc9a',
    storageBucket: 'flutter-e-commerce-app-4cc9a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_JZqtygKVdrF1RrS-6O1CCaZsrW46_Gc',
    appId: '1:840177546760:web:d035cce8b1bc4b031583bd',
    messagingSenderId: '840177546760',
    projectId: 'flutter-e-commerce-app-4cc9a',
    authDomain: 'flutter-e-commerce-app-4cc9a.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-app-4cc9a.firebasestorage.app',
    measurementId: 'G-0CK3BK5TQL',
  );
}
